#ifdef _M_X64

/* This file generated by gen-bases.c - DO NOT EDIT. */

#if GMP_NUMB_BITS != 64
#error error, this data is for 64 bits
#endif

/* mp_bases[10] data, as literal values */
#define MP_BASES_CHARS_PER_LIMB_10      19
#define MP_BASES_BIG_BASE_10            CNST_LIMB(0x8ac7230489e80000)
#define MP_BASES_BIG_BASE_INVERTED_10   CNST_LIMB(0xd83c94fb6d2ac34a)
#define MP_BASES_NORMALIZATION_STEPS_10 0

#else /* _M_X64 */

/* This file generated by gen-bases.c - DO NOT EDIT. */

#if GMP_NUMB_BITS != 32
#error error, this data is for 32 bits
#endif

/* mp_bases[10] data, as literal values */
#define MP_BASES_CHARS_PER_LIMB_10      9
#define MP_BASES_BIG_BASE_10            CNST_LIMB(0x3b9aca00)
#define MP_BASES_BIG_BASE_INVERTED_10   CNST_LIMB(0x12e0be82)
#define MP_BASES_NORMALIZATION_STEPS_10 2

#endif
