#ifdef _M_X64

/* This file generated by gen-fib.c - DO NOT EDIT. */

#if GMP_NUMB_BITS != 64
#error error, this data is for 64 bits
#endif

#define FIB_TABLE_LIMIT         93
#define FIB_TABLE_LUCNUM_LIMIT  92

#else /* _M_X64 */

/* This file generated by gen-fib.c - DO NOT EDIT. */

#if GMP_NUMB_BITS != 32
#error error, this data is for 32 bits
#endif

#define FIB_TABLE_LIMIT         47
#define FIB_TABLE_LUCNUM_LIMIT  46

#endif
