#ifndef XMLRPC_C_VERSION_INCLUDED 
#define XMLRPC_C_VERSION_INCLUDED 
/* generated by Windows/mkvers.bat on 2015/01/03 by swpustc ... */ 
#define XMLRPC_C_VERSION "1.39.0" 
#define XMLRPC_VERSION_MAJOR 1 
#define XMLRPC_VERSION_MINOR 39 
#define XMLRPC_VERSION_POINT 0 
#endif 
